services:
  mongo:
    image: mongo:latest
    container_name: momsrecipebox-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "${MONGODB_ROOT_USER}", "-p", "${MONGODB_ROOT_PASSWORD}", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: momsrecipebox-mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "8081:8081"

  db-init:
    build:
      context: ./db
    container_name: momsrecipebox-db-init
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"

  app:
    container_name: momsrecipebox-app
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@mongo:27017/${MONGODB_DB_NAME}?authSource=admin
      APP_MODE: ${APP_MODE}
    ports:
      - "3000:3000"
    entrypoint: >
      sh -c "if [ \"$APP_MODE\" = 'lambda' ]; then
               /lambda-entrypoint.sh lambda.handler;
             else
               node local_server.js;
             fi"

volumes:
  mongodata:
