services:
  mrb-postgres:
    image: postgres:15
    container_name: momsrecipebox-db
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: momsrecipebox-app
    build:
      context: ./app
    depends_on:
      mrb-postgres:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      PGHOST: mrb-postgres
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_NAME
    ports:
      - "3000:3000"
    command: [ "node", "local_server.js" ]  # This line overrides CMD in Dockerfile
    entrypoint: ["node", "local_server.js"]

volumes:
  pgdata:
    external: true
    name: momsrecipebox_pgdata
