services:
  # Conditionally start MongoDB based on MONGODB_MODE env variable
  # Will only run if MONGODB_MODE is 'local' (default) or not set
  mongo:
    image: mongo:latest
    container_name: momsrecipebox-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_LOCAL_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_LOCAL_ROOT_PASSWORD:-supersecret}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-moms_recipe_box_dev}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "${MONGODB_LOCAL_ROOT_USER:-admin}", "-p", "${MONGODB_LOCAL_ROOT_PASSWORD:-supersecret}", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Only start this service in local mode (not atlas)
    profiles:
      - local

  # MongoDB Express - only run in local mode
  mongo-express:
    image: mongo-express:latest
    container_name: momsrecipebox-mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_LOCAL_ROOT_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_LOCAL_ROOT_PASSWORD:-supersecret}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_LOCAL_ROOT_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_LOCAL_ROOT_PASSWORD:-supersecret}
    ports:
      - "8081:8081"
    # Only start this service in local mode (not atlas)
    profiles:
      - local

  # DB init is only needed in local mode and only if using a fresh DB
  # This should typically be run manually when needed, not automatically
  db-init:
    build:
      context: ./db
    container_name: momsrecipebox-db-init
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    profiles:
      - db-init

  # App with local MongoDB dependency
  app-local:
    container_name: momsrecipebox-app-local
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_LOCAL_URI:-mongodb://${MONGODB_LOCAL_ROOT_USER:-admin}:${MONGODB_LOCAL_ROOT_PASSWORD:-supersecret}@mongo:27017/${MONGODB_DB_NAME:-moms_recipe_box_dev}?authSource=admin}
      APP_MODE: ${APP_MODE:-express}
      MONGODB_MODE: local
    ports:
      - "3000:3000"
    entrypoint: >
      sh -c "if [ \"$APP_MODE\" = 'lambda' ]; then
               /lambda-entrypoint.sh lambda.handler;
             else
               node local_server.js;
             fi"
    depends_on:
      mongo:
        condition: service_healthy
    profiles:
      - local

  # App with Atlas MongoDB connection
  app-atlas:
    container_name: momsrecipebox-app-atlas
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env  # Only base configuration, no secrets
    environment:
      APP_MODE: ${APP_MODE:-express}
      MONGODB_MODE: atlas
      AWS_SECRET_NAME: ${AWS_SECRET_NAME:-moms-recipe-secrets-dev}
      AWS_REGION: ${AWS_REGION:-us-west-2}
      AWS_PROFILE: ${AWS_PROFILE}
      HOME: /root
    volumes:
      # Mount AWS credentials from host
      - ${USERPROFILE}/.aws:/root/.aws:ro
    ports:
      - "3000:3000"
    entrypoint: >
      sh -c "
        echo '🔐 Retrieving secrets from AWS Secrets Manager...';
        
        SECRET_JSON=$$(aws secretsmanager get-secret-value --secret-id \"$${AWS_SECRET_NAME:-moms-recipe-secrets-dev}\" --region \"$${AWS_REGION:-us-west-2}\" --query SecretString --output text);
        
        if [ $$? -ne 0 ]; then
          echo '❌ Failed to retrieve secrets from AWS Secrets Manager';
          exit 1;
        fi;
        
        echo '✅ Secrets retrieved successfully';
        
        export MONGODB_ATLAS_URI=$$(echo \"$$SECRET_JSON\" | jq -r '.MONGODB_ATLAS_URI // empty');
        export MONGODB_URI=\"$$MONGODB_ATLAS_URI\";
        export OPENAI_API_KEY=$$(echo \"$$SECRET_JSON\" | jq -r '.OPENAI_API_KEY // empty');
        export GOOGLE_API_KEY=$$(echo \"$$SECRET_JSON\" | jq -r '.GOOGLE_API_KEY // empty');
        export GROQ_API_KEY=$$(echo \"$$SECRET_JSON\" | jq -r '.GROQ_API_KEY // empty');
        export ANTHROPIC_API_KEY=$$(echo \"$$SECRET_JSON\" | jq -r '.ANTHROPIC_API_KEY // empty');
        export DEEPSEEK_API_KEY=$$(echo \"$$SECRET_JSON\" | jq -r '.DEEPSEEK_API_KEY // empty');
        export AUTH0_DOMAIN=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_DOMAIN // empty');
        export AUTH0_M2M_CLIENT_ID=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_M2M_CLIENT_ID // empty');
        export AUTH0_M2M_CLIENT_SECRET=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_M2M_CLIENT_SECRET // empty');
        export AUTH0_MRB_CLIENT_ID=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_MRB_CLIENT_ID // empty');
        export AUTH0_API_AUDIENCE=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_API_AUDIENCE // empty');
        export AUTH0_MANAGEMENT_AUDIENCE=$$(echo \"$$SECRET_JSON\" | jq -r '.AUTH0_MANAGEMENT_AUDIENCE // empty');
        
        echo '🚀 Starting application with secrets loaded...';
        
        if [ \"$$APP_MODE\" = 'lambda' ]; then
          /lambda-entrypoint.sh lambda.handler;
        else
          node local_server.js;
        fi
      "
    profiles:
      - atlas

volumes:
  mongodata:

# By default, Docker Compose will start services with no profile or with profiles that match the profile names passed via --profile
# This means:
# - For local MongoDB: docker compose --profile local up
# - For Atlas MongoDB: docker compose --profile atlas up
# Since 'local' is the default profile, running just 'docker compose up' will use local MongoDB
