services:
  db:
    image: postgres:15
    container_name: mrb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mrb_admin
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: mrb_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrb_admin -d mrb_dev"]
      interval: 5s
      retries: 5

volumes:
  postgres_data: