openapi: 3.0.0
info:
  title: MomsRecipeBox API
  description: API documentation for the MomsRecipeBox backend
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://sar6jpcqz1.execute-api.us-west-2.amazonaws.com/dev

paths:
  /recipes:
    post:
      summary: Create a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '201':
          description: Recipe created
    get:
      summary: Get a list of recipes
      parameters:
      - in: query
        name: owner_id
        schema:
          type: string
      - in: query
        name: visibility
        schema:
          type: string
      - in: query
        name: tags
        schema:
          type: string
      - in: query
        name: expand
        schema:
          type: string
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: offset
        schema:
          type: integer
      responses:
        '200':
          description: List of recipes

  /recipes/{id}:
    get:
      summary: Get a specific recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: expand
        schema:
          type: string
      responses:
        '200':
          description: A single recipe
    put:
      summary: Update a specific recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '200':
          description: Recipe updated
    delete:
      summary: Delete a recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Recipe deleted

  /recipes/{id}/comments:
    post:
      summary: Post a comment on a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '200':
          description: Comment added

  /comments/{comment_id}:
    put:
      summary: Update a comment
      parameters:
      - in: path
        name: comment_id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '200':
          description: Comment updated
    delete:
      summary: Delete a comment
      parameters:
      - in: path
        name: comment_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Comment deleted

  /recipes/{id}/like:
    post:
      summary: Toggle like for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      responses:
        '200':
          description: Like toggled
  /recipes/{id}/image:
    post:
      summary: Upload an image for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageBase64:
                  type: string
                contentType:
                  type: string
      responses:
        '200':
          description: Image uploaded successfully
    put:
      summary: Update an image for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageBase64:
                  type: string
                contentType:
                  type: string
      responses:
        '200':
          description: Image updated successfully
    delete:
      summary: Delete an image for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Image deleted successfully
    get:
      summary: Get an image for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Image fetched successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Image not found

components:
  schemas:
    RecipeInput:
      type: object
      required:
      - owner_id
      - visibility
      - title
      properties:
        owner_id:
          type: string
        visibility:
          type: string
        status:
          type: string
        title:
          type: string
        subtitle:
          type: string
        description:
          type: string
        image_url:
          type: string
        tags:
          type: array
          items:
            type: string
        sections:
          type: array
          items:
            type: object
            properties:
              section_type:
                type: string
              content:
                type: string
              position:
                type: integer
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              quantity:
                type: string
              position:
                type: integer

    CommentInput:
      type: object
      properties:
        user_id:
          type: string
        content:
          type: string
