openapi: 3.0.0
info:
  title: MomsRecipeBox API
  description: API documentation for the MomsRecipeBox backend
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://sar6jpcqz1.execute-api.us-west-2.amazonaws.com/dev

tags:
  - name: recipes
    description: Recipe management operations
  - name: comments
    description: Recipe comment operations
  - name: likes
    description: Recipe like operations
  - name: images
    description: Recipe image operations
  - name: shopping-list
    description: Shopping list operations

paths:
  /recipes:
    post:
      tags:
        - recipes
      summary: Create a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '201':
          description: Recipe created
    get:
      tags:
        - recipes
      summary: Get a list of recipes
      parameters:
      - in: query
        name: owner_id
        schema:
          type: string
      - in: query
        name: visibility
        schema:
          type: string
      - in: query
        name: tags
        schema:
          type: string
      - in: query
        name: expand
        schema:
          type: string
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: offset
        schema:
          type: integer
      responses:
        '200':
          description: List of recipes

  /recipes/{id}:
    get:
      tags:
        - recipes
      summary: Get a specific recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: expand
        schema:
          type: string
      responses:
        '200':
          description: A single recipe
    put:
      tags:
        - recipes
      summary: Update a specific recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '200':
          description: Recipe updated
    delete:
      tags:
        - recipes
      summary: Delete a recipe by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Recipe deleted

  /recipes/{id}/comments:
    post:
      tags:
        - comments
      summary: Post a comment on a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '200':
          description: Comment added

  /comments/{comment_id}:
    put:
      tags:
        - comments
      summary: Update a comment
      parameters:
      - in: path
        name: comment_id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '200':
          description: Comment updated
    delete:
      tags:
        - comments
      summary: Delete a comment
      parameters:
      - in: path
        name: comment_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Comment deleted

  /recipes/{id}/like:
    post:
      tags:
        - likes
      summary: Toggle like for a recipe
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      responses:
        '200':
          description: Like toggled
  /recipes/{id}/image:
    put:
      tags:
        - images
      summary: Upload or update an image for a recipe
      description: Upload or update an image using base64 encoding. Supports PNG and JPEG formats. Use this method for both initial upload and updates.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Recipe ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageBase64:
                  type: string
                  description: Base64-encoded image data
                contentType:
                  type: string
                  description: Content type of the image (image/png or image/jpeg)
                  enum: [image/png, image/jpeg]
            example:
              imageBase64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
              contentType: "image/png"
      responses:
        '200':
          description: Image updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Image updated successfully!
                  key:
                    type: string
                    example: 60f1e5b0e6b3a123456789ab.png
                  contentType:
                    type: string
                    example: image/png
        '400':
          description: Bad request - invalid input
        '404':
          description: Recipe not found
        '500':
          description: Internal server error
    delete:
      tags:
        - images
      summary: Delete an image for a recipe
      description: Delete a recipe's image. This will revert the recipe to use the default image.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Recipe ID
      responses:
        '200':
          description: Image deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Image deleted successfully!
        '404':
          description: Recipe or image not found
        '500':
          description: Internal server error
    get:
      tags:
        - images
      summary: Get an image for a recipe
      description: Retrieve an image for a recipe. If no image exists for the recipe, returns the default image.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Recipe ID
      - in: header
        name: Accept
        schema:
          type: string
          enum: [image/png, image/jpeg]
        description: Preferred image format (optional)
      responses:
        '200':
          description: Image fetched successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            image/gif:
              schema:
                type: string
                format: binary
        '404':
          description: Recipe not found
        '500':
          description: Internal server error

  /shopping-list:
    get:
      tags:
        - shopping-list
      summary: Get a user's shopping list
      description: Retrieves the shopping list for a specific user
      parameters:
      - in: query
        name: user_id
        required: true
        schema:
          type: string
        description: User ID
      responses:
        '200':
          description: Shopping list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingList'
        '400':
          description: Missing required parameters
        '500':
          description: Internal server error
# The DELETE method on /shopping-list is not used
# Use /shopping-list/clear for clearing the shopping list

  /shopping-list/add:
    post:
      tags:
        - shopping-list
      summary: Add items to a shopping list
      description: Add one or more ingredients to a user's shopping list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - items
              properties:
                user_id:
                  type: string
                  description: User ID
                items:
                  type: array
                  description: List of ingredients to add
                  items:
                    type: object
                    required:
                      - ingredient
                    properties:
                      ingredient:
                        type: string
                        description: Full ingredient text
                      recipe_id:
                        type: string
                        description: ID of the source recipe
                      recipe_title:
                        type: string
                        description: Title of the source recipe
                      category:
                        type: string
                        description: Optional grocery department category
            example:
              user_id: "user123"
              items:
                - ingredient: "2 tbsp olive oil"
                  recipe_id: "5f8a7b6c5d4e3c2b1a0987654"
                  recipe_title: "Mediterranean Pasta"
                - ingredient: "1 onion, diced"
                  recipe_id: "5f8a7b6c5d4e3c2b1a0987654"
                  recipe_title: "Mediterranean Pasta"
      responses:
        '200':
          description: Items added successfully
        '400':
          description: Missing required parameters
        '500':
          description: Internal server error

  /shopping-list/item/{itemId}:
    put:
      tags:
        - shopping-list
      summary: Update a shopping list item
      description: Update the status of an item in a shopping list (e.g., mark as checked)
      parameters:
      - in: path
        name: itemId
        required: true
        schema:
          type: string
        description: Shopping list item ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - checked
              properties:
                user_id:
                  type: string
                  description: User ID
                checked:
                  type: boolean
                  description: Whether the item is checked
      responses:
        '200':
          description: Item updated successfully
        '400':
          description: Missing required parameters
        '404':
          description: Item not found
        '500':
          description: Internal server error
    delete:
      tags:
        - shopping-list
      summary: Remove an item from a shopping list
      description: Delete a specific item from a user's shopping list
      parameters:
      - in: path
        name: itemId
        required: true
        schema:
          type: string
        description: Shopping list item ID
      - in: query
        name: user_id
        required: true
        schema:
          type: string
        description: User ID
      responses:
        '200':
          description: Item removed successfully
        '404':
          description: Item not found
        '500':
          description: Internal server error

  /shopping-list/clear:
    post:
      tags:
        - shopping-list
      summary: Clear a user's shopping list or mark all items as checked
      description: Remove all items from a user's shopping list or mark all as checked
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  description: User ID
                action:
                  type: string
                  enum: [delete_all, check_all]
                  description: Action to perform (delete all items or mark all as checked)
      responses:
        '200':
          description: Shopping list cleared or all items marked as checked
        '400':
          description: Missing required parameters
        '404':
          description: Shopping list not found
        '500':
          description: Internal server error

components:
  schemas:
    ShoppingList:
      type: object
      properties:
        _id:
          type: string
          description: Shopping list ID
        user_id:
          type: string
          description: User ID
        items:
          type: array
          description: List of shopping items
          items:
            type: object
            properties:
              item_id:
                type: string
                description: Unique identifier for the item
              ingredient:
                type: string
                description: Full ingredient text
              recipe_id:
                type: string
                description: ID of the source recipe
              recipe_title:
                type: string
                description: Title of the source recipe
              added_at:
                type: string
                format: date-time
                description: When the item was added
              checked:
                type: boolean
                description: Whether the item has been checked off
              category:
                type: string
                description: Optional grocery department category
        created_at:
          type: string
          format: date-time
          description: When the shopping list was created
        updated_at:
          type: string
          format: date-time
          description: When the shopping list was last updated
      example:
        _id: "60f1e5b0e6b3a123456789ab"
        user_id: "user123"
        items:
          - item_id: "item1"
            ingredient: "2 tbsp olive oil"
            recipe_id: "5f8a7b6c5d4e3c2b1a0987654"
            recipe_title: "Mediterranean Pasta"
            added_at: "2025-08-27T10:30:00Z"
            checked: false
          - item_id: "item2"
            ingredient: "1 onion, diced"
            recipe_id: "5f8a7b6c5d4e3c2b1a0987654"
            recipe_title: "Mediterranean Pasta"
            added_at: "2025-08-27T10:30:00Z"
            checked: true
        created_at: "2025-08-27T10:30:00Z"
        updated_at: "2025-08-27T10:35:00Z"
    
    RecipeInput:
      type: object
      required:
      - owner_id
      - visibility
      - title
      properties:
        owner_id:
          type: string
        visibility:
          type: string
        status:
          type: string
        title:
          type: string
        subtitle:
          type: string
        description:
          type: string
        image_url:
          type: string
        tags:
          type: array
          items:
            type: string
        sections:
          type: array
          items:
            type: object
            properties:
              section_type:
                type: string
              content:
                type: string
              position:
                type: integer
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              quantity:
                type: string
              position:
                type: integer

    CommentInput:
      type: object
      properties:
        user_id:
          type: string
        content:
          type: string
