  /recipes/ai-chat:
    post:
      tags:
        - recipes
        - ai
      summary: Chat with AI to create recipes
      description: Converse with an AI assistant to create, modify, or get help with recipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: User's message in the chat
                history:
                  type: array
                  description: Previous messages in the conversation
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [user, assistant]
                      content:
                        type: string
                user_id:
                  type: string
                  description: ID of the user
            example:
              message: "Create a recipe for chocolate chip cookies"
              history: [
                {
                  "role": "user",
                  "content": "I want to make cookies"
                },
                {
                  "role": "assistant",
                  "content": "What kind of cookies would you like to make?"
                }
              ]
              user_id: "demo-user"
      responses:
        '200':
          description: AI response with optional recipe data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    description: AI response message
                  recipeData:
                    type: object
                    description: Structured recipe data (if a complete recipe was generated)
                    properties:
                      title:
                        type: string
                      subtitle:
                        type: string
                      description:
                        type: string
                      author:
                        type: string
                      source:
                        type: string
                      yield:
                        type: string
                      time:
                        type: object
                      ingredients:
                        type: array
                        items:
                          type: object
                          properties:
                            quantity:
                              type: string
                            name:
                              type: string
                      steps:
                        type: array
                        items:
                          type: string
                      tags:
                        type: array
                        items:
                          type: string
                      notes:
                        type: string
        '400':
          description: Invalid request
        '500':
          description: Server error
          
  /recipes/extract-url:
    post:
      tags:
        - recipes
        - ai
      summary: Extract recipe from URL
      description: Parse a webpage URL to extract structured recipe data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: URL of the recipe webpage to extract
                user_id:
                  type: string
                  description: ID of the user
            example:
              url: "https://example.com/recipe-page"
              user_id: "demo-user"
      responses:
        '200':
          description: Extracted recipe data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    description: Status message
                  recipeData:
                    type: object
                    description: Structured recipe data extracted from the URL
                    properties:
                      title:
                        type: string
                      subtitle:
                        type: string
                      description:
                        type: string
                      author:
                        type: string
                      source:
                        type: string
                      yield:
                        type: string
                      time:
                        type: object
                      ingredients:
                        type: array
                        items:
                          type: object
                          properties:
                            quantity:
                              type: string
                            name:
                              type: string
                      steps:
                        type: array
                        items:
                          type: string
                      tags:
                        type: array
                        items:
                          type: string
                      notes:
                        type: string
        '400':
          description: Invalid request or URL
        '500':
          description: Server error or extraction failed
