#!/usr/bin/env node

/**
 * Profile Manager for Mom's Recipe Box
 * Manages deployment profiles and environment configuration
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const CONFIG_DIR = path.join(ROOT_DIR, 'config');
const PROFILES_FILE = path.join(CONFIG_DIR, 'deployment-profiles.json');
const CURRENT_PROFILE_FILE = path.join(CONFIG_DIR, 'current-profile.env');
const ROOT_ENV_FILE = path.join(ROOT_DIR, '.env');

// ANSI color codes
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function showBanner() {
  const banner = `
 ╔═══════════════════════════════════════════════╗
 ║  Profile Manager for Mom's Recipe Box         ║
 ║  Four-Profile Deployment Architecture         ║
 ╚═══════════════════════════════════════════════╝`;
  log(banner, 'cyan');
}

// Load deployment profiles
function loadProfiles() {
  if (!fs.existsSync(PROFILES_FILE)) {
    log(`❌ Profiles file not found: ${PROFILES_FILE}`, 'red');
    process.exit(1);
  }
  
  try {
    const content = fs.readFileSync(PROFILES_FILE, 'utf8');
    return JSON.parse(content);
  } catch (error) {
    log(`❌ Error loading profiles: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Save deployment profiles
function saveProfiles(profiles) {
  try {
    const content = JSON.stringify(profiles, null, 2);
    fs.writeFileSync(PROFILES_FILE, content);
    log(`✅ Profiles saved to ${PROFILES_FILE}`, 'green');
  } catch (error) {
    log(`❌ Error saving profiles: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Load environment variables from root .env
function loadStaticEnv() {
  const env = {};
  
  if (fs.existsSync(ROOT_ENV_FILE)) {
    const content = fs.readFileSync(ROOT_ENV_FILE, 'utf8');
    const lines = content.split('\n');
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        if (key && valueParts.length > 0) {
          env[key.trim()] = valueParts.join('=').trim();
        }
      }
    }
  }
  
  return env;
}

// Replace environment variable placeholders
function replaceEnvVars(value, env) {
  if (typeof value !== 'string') return value;
  
  return value.replace(/\$\{([^}]+)\}/g, (match, varName) => {
    return env[varName] || process.env[varName] || match;
  });
}

// Generate current profile environment file
function generateCurrentProfileEnv(profileName, profile, staticEnv) {
  const lines = [
    '# Generated by profile-manager.js - DO NOT EDIT MANUALLY',
    `# Profile: ${profileName} - ${profile.name}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    `CURRENT_PROFILE=${profileName}`
  ];
  
  // Add profile-specific environment variables
  for (const [key, value] of Object.entries(profile.environment)) {
    const resolvedValue = replaceEnvVars(value, staticEnv);
    lines.push(`${key}=${resolvedValue}`);
  }
  
  // Add computed values
  if (profile.database.connectionString) {
    const mongoUri = replaceEnvVars(profile.database.connectionString, staticEnv);
    lines.push(`MONGODB_URI=${mongoUri}`);
  }
  
  if (profile.frontend.apiUrl) {
    const apiUrl = replaceEnvVars(profile.frontend.apiUrl, staticEnv);
    lines.push(`API_BASE_URL=${apiUrl}`);
  }
  
  const content = lines.join('\n') + '\n';
  
  try {
    fs.writeFileSync(CURRENT_PROFILE_FILE, content);
    log(`✅ Generated ${CURRENT_PROFILE_FILE}`, 'green');
  } catch (error) {
    log(`❌ Error writing current profile file: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Set current profile
function setProfile(profileName) {
  const profiles = loadProfiles();
  
  if (!profiles.profiles[profileName]) {
    log(`❌ Profile '${profileName}' not found`, 'red');
    log(`Available profiles: ${Object.keys(profiles.profiles).join(', ')}`, 'yellow');
    process.exit(1);
  }
  
  const profile = profiles.profiles[profileName];
  const staticEnv = loadStaticEnv();
  
  log(`🔄 Setting profile to: ${profileName} (${profile.name})`, 'blue');
  
  // Update current profile in config
  profiles.currentProfile = profileName;
  profiles.metadata.lastUpdated = new Date().toISOString();
  saveProfiles(profiles);
  
  // Generate current profile environment file
  generateCurrentProfileEnv(profileName, profile, staticEnv);
  
  log(`✅ Profile set to ${profileName}`, 'green');
  log(`📝 Description: ${profile.description}`, 'cyan');
}

// Show current profile
function showProfile() {
  const profiles = loadProfiles();
  const currentProfileName = profiles.currentProfile;
  const currentProfile = profiles.profiles[currentProfileName];
  
  if (!currentProfile) {
    log(`❌ Current profile '${currentProfileName}' not found`, 'red');
    return;
  }
  
  log(`\n📊 Current Profile: ${currentProfileName}`, 'cyan');
  log(`📝 Name: ${currentProfile.name}`, 'blue');
  log(`📋 Description: ${currentProfile.description}`, 'blue');
  log(`\n🏗️  Architecture:`, 'yellow');
  log(`   Database: ${currentProfile.database.type}`, 'white');
  log(`   Backend: ${currentProfile.backend.type}`, 'white');
  log(`   Frontend: ${currentProfile.frontend.type}`, 'white');
  
  if (currentProfile.docker.services.length > 0) {
    log(`\n🐳 Docker Services:`, 'yellow');
    currentProfile.docker.services.forEach(service => {
      log(`   - ${service}`, 'white');
    });
  }
  
  log(`\n🔧 Environment Variables:`, 'yellow');
  for (const [key, value] of Object.entries(currentProfile.environment)) {
    log(`   ${key}=${value}`, 'white');
  }
}

// List all profiles
function listProfiles() {
  const profiles = loadProfiles();
  const currentProfileName = profiles.currentProfile;
  
  log(`\n📋 Available Profiles:`, 'cyan');
  
  for (const [name, profile] of Object.entries(profiles.profiles)) {
    const current = name === currentProfileName ? ' (current)' : '';
    log(`\n${name}${current}`, current ? 'green' : 'blue');
    log(`  ${profile.description}`, 'white');
    log(`  Database: ${profile.database.type} | Backend: ${profile.backend.type} | Frontend: ${profile.frontend.type}`, 'white');
  }
}

// Start infrastructure for current profile
function startInfrastructure() {
  const profiles = loadProfiles();
  const currentProfileName = profiles.currentProfile;
  const currentProfile = profiles.profiles[currentProfileName];
  
  log(`🚀 Starting infrastructure for profile: ${currentProfileName}`, 'blue');
  
  if (currentProfile.docker.services.length === 0) {
    log(`ℹ️  Profile '${currentProfileName}' uses external services - no local infrastructure to start`, 'yellow');
    return;
  }
  
  try {
    const dockerProfile = currentProfile.docker.profile;
    if (dockerProfile) {
      log(`🐳 Starting Docker services with profile: ${dockerProfile}`, 'blue');
      execSync(`docker-compose --profile ${dockerProfile} up -d`, { 
        stdio: 'inherit',
        cwd: ROOT_DIR
      });
      log(`✅ Infrastructure started successfully`, 'green');
    }
  } catch (error) {
    log(`❌ Error starting infrastructure: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Stop infrastructure for current profile
function stopInfrastructure() {
  const profiles = loadProfiles();
  const currentProfileName = profiles.currentProfile;
  
  log(`🛑 Stopping infrastructure for profile: ${currentProfileName}`, 'blue');
  
  try {
    // Stop all profiles to ensure clean state
    execSync('docker-compose --profile local --profile atlas down', { 
      stdio: 'inherit',
      cwd: ROOT_DIR
    });
    log(`✅ Infrastructure stopped successfully`, 'green');
  } catch (error) {
    log(`❌ Error stopping infrastructure: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Validate current profile
function validateProfile() {
  const profiles = loadProfiles();
  const currentProfileName = profiles.currentProfile;
  const currentProfile = profiles.profiles[currentProfileName];
  
  log(`🔍 Validating profile: ${currentProfileName}`, 'blue');
  
  const staticEnv = loadStaticEnv();
  let valid = true;
  
  // Check required environment variables
  const requiredVars = ['MONGODB_DB_NAME', 'AWS_REGION', 'RECIPE_IMAGES_BUCKET'];
  
  for (const varName of requiredVars) {
    if (!staticEnv[varName] && !process.env[varName]) {
      log(`❌ Missing required environment variable: ${varName}`, 'red');
      valid = false;
    }
  }
  
  // Check profile-specific requirements
  if (currentProfile.database.type === 'atlas') {
    if (!staticEnv.MONGODB_ATLAS_URI && !process.env.MONGODB_ATLAS_URI) {
      log(`❌ Missing MONGODB_ATLAS_URI for atlas database`, 'red');
      valid = false;
    }
  }
  
  if (currentProfile.backend.type === 'lambda') {
    if (!staticEnv.LAMBDA_API_URL && !process.env.LAMBDA_API_URL) {
      log(`❌ Missing LAMBDA_API_URL for lambda backend`, 'red');
      valid = false;
    }
  }
  
  if (valid) {
    log(`✅ Profile validation passed`, 'green');
  } else {
    log(`❌ Profile validation failed`, 'red');
    process.exit(1);
  }
}

// Show usage
function showUsage() {
  console.log(`
🔄 Profile Manager for Mom's Recipe Box

Usage: node scripts/profile-manager.js <command> [options]

Commands:
  show                    Show current profile details
  list                    List all available profiles
  set <profile>          Set active profile (local|atlas|lambda|cloud)
  start                  Start infrastructure for current profile
  stop                   Stop all infrastructure
  validate               Validate current profile configuration
  dev                    Start development environment for current profile

Examples:
  node scripts/profile-manager.js show
  node scripts/profile-manager.js set local
  node scripts/profile-manager.js start
  node scripts/profile-manager.js dev

NPM Shortcuts:
  npm run profile:show
  npm run profile:set local
  npm run profile:local
  npm run start
  npm run dev
`);
}

// Main function
function main() {
  const args = process.argv.slice(2);
  
  if (args.length === 0) {
    showBanner();
    showUsage();
    return;
  }
  
  const command = args[0];
  
  switch (command) {
    case 'show':
      showProfile();
      break;
    case 'list':
      listProfiles();
      break;
    case 'set':
      if (args.length < 2) {
        log('❌ Profile name required', 'red');
        log('Usage: npm run profile:set <profile>', 'yellow');
        process.exit(1);
      }
      setProfile(args[1]);
      break;
    case 'start':
      startInfrastructure();
      break;
    case 'stop':
      stopInfrastructure();
      break;
    case 'validate':
      validateProfile();
      break;
    case 'dev':
      // Start development environment (infrastructure + UI if needed)
      startInfrastructure();
      // TODO: Add UI startup logic based on profile
      break;
    case 'help':
    case '--help':
      showUsage();
      break;
    default:
      log(`❌ Unknown command: ${command}`, 'red');
      showUsage();
      process.exit(1);
  }
}

// Run main function
main();

export { 
  loadProfiles, 
  setProfile, 
  showProfile, 
  listProfiles, 
  startInfrastructure, 
  stopInfrastructure,
  validateProfile 
};