name: Code Quality Validation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: "Code Quality & Security"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Updated to match markdownlint requirements
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
        
    - name: Install dependencies
      run: |
        cd app
        npm ci
        
    - name: Run unit tests
      run: |
        cd app
        npm test
        
    - name: Check for security vulnerabilities
      run: |
        cd app
        npm audit --audit-level=high
        
    - name: Validate Docker configuration
      run: |
        # Check docker-compose.yml syntax
        docker-compose config > /dev/null
        echo "✅ Docker Compose configuration is valid"